version: '3'
services:
  jenkins:
    restart: always
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      
  gitlab:
      container_name: gitlab
      image: 'gitlab/gitlab-ce:latest'
      restart: always
      hostname: 'localhost'
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'localhost:8929'
          # Add any other gitlab.rb configuration here, each on its own line
          gitlab_rails['gitlab_shell_ssh_port'] = 2224
      ports:
        - '8929:8929'
        - '2224:22'
        - '9000:80'

      volumes:
        - '$GITLAB_HOME/config:/etc/gitlab'
        - '$GITLAB_HOME/logs:/var/log/gitlab'
        - '$GITLAB_HOME/data:/var/opt/gitlab'

    registry:
      image: registry
      container_name: registry
      restart: always
      ports:
        - 5000:5000
